version: '3.9'

services:
  backend:
    image: uon_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
  
  client:
    image: uon_client
    build:
      context: ../../uf/uonfront/uon
      dockerfile: Dockerfile
    ports:
      - "5001:3000"
    
  proxy:
    image: nginx:mainline
    volumes:
      - ../../uf/uonfront/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80